
using Microsoft.EntityFrameworkCore;

namespace disneylandvotingapp.Api.Model
{
    public class ApplicationDbContext : DbContext
    {
        public DbSet<ApplicationUser> Users { get; set; }
        public DbSet<Character> Characters { get; set; }
        public DbSet<Vote> Votes { get; set; }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Character>()
                .Property(c => c.Id)
                .ValueGeneratedOnAdd();  // This configures the ID to be generated by the database

            modelBuilder.Entity<Character>()
                .HasMany(c => c.Votes)
                .WithOne(v => v.Character)
                .HasForeignKey(v => v.CharacterId);

            modelBuilder.Entity<Vote>()
                .Property(v => v.Id)
                .ValueGeneratedOnAdd();

            modelBuilder.Entity<ApplicationUser>()
                .Property(u => u.Id)
                .ValueGeneratedOnAdd();
        }
    }
}
